# Tensorflow basics

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


Summary of this notebook:
* Creating constant tensor
* Creating Variable tensor
* Change value stored in variable tensor
* Get tensor attributes ->
1. `<tensor>.shape`
2. `<tensor>.ndim`
3. `tf.size(<tensor>)`
* Shuffle tensors
* Create random (uniform or normal) tensors
* Concept of global and opertional level seed
* Add new dimension (Using: `expand_dim` and `tf.newaxis`)

In [2]:
scalar = tf.constant(42)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
vector.ndim

1

In [5]:
matrix = tf.constant([[1, 2], [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [6]:
matrix.ndim

2

In [7]:
another_matrix = tf.constant([[1., 2.],
                              [2., 5.],
                              [7., 2.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [2., 5.],
       [7., 2.]], dtype=float16)>

In [8]:
another_matrix.ndim

2

In [9]:
tensor = tf.constant([[[1, 2, 5],
                      [3, 4, 6]],
                      [[4, 5, 8],
                       [6, 7, 10]],
                      [[1,2,3],
                       [90, 10, 110]]], dtype=tf.int16)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int16, numpy=
array([[[  1,   2,   5],
        [  3,   4,   6]],

       [[  4,   5,   8],
        [  6,   7,  10]],

       [[  1,   2,   3],
        [ 90,  10, 110]]], dtype=int16)>

In [10]:
tensor.ndim

3

In [11]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [12]:
changeble_variable = tf.Variable([10, 7])
unchangeble_variable = tf.constant([10, 7])
changeble_variable, unchangeble_variable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
changeble_variable[0] = 7

TypeError: ignored

In [14]:
changeble_variable[0].assign(7)
changeble_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
unchangeble_variable[0] = 100

TypeError: ignored

In [16]:
unchangeble_variable[0].assign(100)

AttributeError: ignored

In [17]:
changeble_variable.assign([100, 10])
changeble_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([100,  10], dtype=int32)>

### Random tensors

In [18]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(2,3))
random1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [19]:
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(2,3))
random2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [20]:
random1, random2, random1 == random2

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True]])>)

In [21]:
tf.random.uniform(shape=(2,2), seed=10), tf.random.uniform(shape=(2,2), seed=10)

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.1585741 , 0.16258383],
        [0.40983236, 0.19529402]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.06444478, 0.95510364],
        [0.24339306, 0.01308858]], dtype=float32)>)

In [22]:
rand1 = tf.random.Generator.from_seed(42)
rand2 = tf.random.Generator.from_seed(42)

rand1.uniform(shape=(2,2)), rand2.uniform(shape=(2,2))

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817]], dtype=float32)>)

### Shuffle order of elements in Tensor

In [23]:
not_shuffled = tf.constant([[10, 7],
                            [7,3],
                            [42, 21]])
shuffled = tf.random.shuffle(not_shuffled, seed=42)
not_shuffled, shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7,  3],
        [42, 21]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[42, 21],
        [ 7,  3],
        [10,  7]], dtype=int32)>)

In [24]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7,  3],
       [42, 21]], dtype=int32)>

In [25]:
tf.random.set_seed(42)
tf.random.uniform(shape=(1,1))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.6645621]], dtype=float32)>

### Other wasy to make tensors

In [26]:
tf.ones([3,4], dtype=tf.float16)

<tf.Tensor: shape=(3, 4), dtype=float16, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float16)>

In [27]:
tf.zeros([3,4], dtype=tf.int16)

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [28]:
tf.zeros(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn numpy array into tensors
Main difference is that tensors can run in GPU and TPU

In [29]:
import numpy as np
numpy_A = np.arange(1, 10, dtype=np.int16)
numpy_A

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [30]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(9,), dtype=int16, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)>

In [31]:
B = tf.constant(numpy_A, shape=(3,3))
B

<tf.Tensor: shape=(3, 3), dtype=int16, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)>

### Getting information from tensors

* Shape -> tf.shape
* Rank -> tf.ndim
* Axis or dimension - > A[0], A[:, :]
* Size -> tf.size(<>)


In [32]:
rank_4_tensor = tf.ones(shape=(2,3,4,5), dtype=tf.int32)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int32)>

In [33]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [34]:
rank_4_tensor.ndim

4

In [35]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [36]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int32)>

In [37]:
print("Total number of elements in the tensor: ", tf.size(rank_4_tensor).numpy())
print("Type of each element of the Tensor: ", rank_4_tensor.dtype)
print("Number of elements along last axis: ", rank_4_tensor.shape[-1])
print("Rank of the tensor: ", rank_4_tensor.ndim)

Total number of elements in the tensor:  120
Type of each element of the Tensor:  <dtype: 'int32'>
Number of elements along last axis:  5
Rank of the tensor:  4


### Indexing
works same way as python list

In [38]:
# get first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]], dtype=int32)>

In [39]:
rank_4_tensor[:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int32)>

In [40]:
rank_4_tensor[:2, :2, :2, :]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int32)>

In [41]:
rank_2_tensor = tf.constant([[1, 5],
                             [4, 5]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 5],
       [4, 5]], dtype=int32)>

In [42]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>

In [43]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [5]],

       [[4],
        [5]]], dtype=int32)>

In [44]:
rank_2_tensor[tf.newaxis, ...]

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 5],
        [4, 5]]], dtype=int32)>

In [45]:
rank_2_tensor[:, tf.newaxis, :]

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 5]],

       [[4, 5]]], dtype=int32)>

In [46]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [5]],

       [[4],
        [5]]], dtype=int32)>

In [47]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 5],
        [4, 5]]], dtype=int32)>

In [48]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 5]],

       [[4, 5]]], dtype=int32)>

### Manupulating tensors (Tensor operations)
**Basic operations**

In [49]:
some_tensor = tf.constant([[10, 7], [7, 3]])
some_tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [17, 13]], dtype=int32)>

In [50]:
some_tensor = some_tensor + 10
some_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [17, 13]], dtype=int32)>

In [51]:
some_tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [170, 130]], dtype=int32)>

In [52]:
some_tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7,  3]], dtype=int32)>

In [53]:
some_tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[10. ,  8.5],
       [ 8.5,  6.5]])>

In [54]:
tf.add(some_tensor, 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 18],
       [18, 14]], dtype=int32)>

In [57]:
tf.subtract(some_tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 14],
       [14, 10]], dtype=int32)>

In [58]:
tf.divide(some_tensor, [[2,2], [3,3]])

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[10.        ,  8.5       ],
       [ 5.66666667,  4.33333333]])>

**Matrix Multiplication**

In [59]:
A = tf.constant([[1,2], [3,4]])
B = tf.constant([[4,5], [6,7]])
A, B

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 5],
        [6, 7]], dtype=int32)>)

In [60]:
tf.linalg.matmul(A, B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 19],
       [36, 43]], dtype=int32)>

In [63]:
## matmul is usual matrix multiplication, and * is element wise multiplication
tf.matmul(A, B), A * B

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[16, 19],
        [36, 43]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 4, 10],
        [18, 28]], dtype=int32)>)

In [66]:
# This is python operator for matrix multiplication
A @ B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 19],
       [36, 43]], dtype=int32)>

In [67]:
X = tf.constant([[1, 2], [3, 4], [5,6]])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [68]:
tf.reshape(X, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [69]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

**Reshape and Transpose works differently**

In [72]:
X, tf.reshape(X, shape=(2,3)), tf.transpose(X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

**Matrix multiplication using @ and matmul**

In [75]:
Y = tf.constant([[1,2,3], [4,5,6]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [77]:
# using matmul operator
tf.matmul(X, Y), tf.matmul(Y, X)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[22, 28],
        [49, 64]], dtype=int32)>)

In [78]:
X @ Y, Y @ X

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[22, 28],
        [49, 64]], dtype=int32)>)

In [80]:
tf.tensordot(X, Y, axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

### Changing datatype of tensors

In [84]:
B = tf.constant([[1.7, 2.3], [3.14, 2.78]])
B, B.dtype

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1.7 , 2.3 ],
        [3.14, 2.78]], dtype=float32)>, tf.float32)

In [85]:
C = tf.cast(B, tf.float16)
C, C.dtype

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[1.7 , 2.3 ],
        [3.14, 2.78]], dtype=float16)>, tf.float16)

### Aggregating tensors
* abs - `tf.abs`
* min - `tf.reduce_mean(tensor, axis, keepdims)`
* max - `tf.reduce_max(tensor, axis, keepdims)`
* mean - `tf.reduce_mean(tensor, axis, keepdims)`
* sum - `tf.reduce_sum(tensor, axis, keepdims)`
* Variance - `tf.math.reduce_variance(tensor, axis, keepdims)`
* Standard Deviation - `tf.math.reduce_std(tensor, axis, keepdims)`
* Can do other things also - `tf.math.reduce_logsumexp`, `tf.math.reduce_prod`, `tf.math.reduce_euclidien_norm`, etc.

In [87]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [88]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [92]:
Y = tf.constant([[1, 2], [3, 4]], dtype=tf.float16)
Y

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [93]:
tf.reduce_mean(Y, axis = 1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[1.5],
       [3.5]], dtype=float16)>

In [94]:
tf.reduce_max(Y, axis = 1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[2.],
       [4.]], dtype=float16)>

In [95]:
tf.reduce_min(Y, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 2), dtype=float16, numpy=array([[1., 2.]], dtype=float16)>

In [97]:
tf.reduce_sum(Y, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 2), dtype=float16, numpy=array([[4., 6.]], dtype=float16)>

In [101]:
tf.math.reduce_variance(Y, axis=1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[0.25],
       [0.25]], dtype=float16)>

In [102]:
tf.math.reduce_std(Y, axis=1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[0.5],
       [0.5]], dtype=float16)>

In [104]:
tf.math.reduce_logsumexp(Y)

<tf.Tensor: shape=(), dtype=float16, numpy=4.44>

In [105]:
tf.math.reduce_logsumexp(Y, axis=1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
array([[2.312],
       [4.312]], dtype=float16)>

### Find positional maximum and minimum

In [106]:
X = tf.constant([[1, 3], [4, 5], [10, 6]])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 4,  5],
       [10,  6]], dtype=int32)>

In [108]:
tf.argmax(X, axis=0)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2])>

In [113]:
tf.argmax(X, axis=1).numpy()

array([1, 1, 0])

In [114]:
X[tf.argmax(X, axis=1).numpy(), :]

TypeError: ignored

In [115]:
tf.reduce_max(X, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3,  5, 10], dtype=int32)>

### Squeezing a tensor
Removes all 1 dimesions from the dimensions

In [119]:
tf.random.set_seed(42)
G = tf.random.uniform(shape=[1,1,1,1,10])
G.shape

TensorShape([1, 1, 1, 1, 10])

In [121]:
G1 = tf.squeeze(G)
G.shape, G1.shape

(TensorShape([1, 1, 1, 1, 10]), TensorShape([10]))

### One hot encoding tensors

In [130]:
some_list = [[0, 1, 2, 3], [4,5,6,7]]
some_tensor = [[0, 1, 2, 3], [4,5,6,7]]

In [129]:
one_h = tf.one_hot(some_list, depth=8)
one_h, one_h.shape

(<tf.Tensor: shape=(2, 4, 8), dtype=float32, numpy=
 array([[[1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1.]]], dtype=float32)>,
 TensorShape([2, 4, 8]))

In [134]:
one_h2 = tf.one_hot([[0, 1], [2, 3]], depth=4, on_value="I love Arya", off_value="I don't like dancing")
one_h2

<tf.Tensor: shape=(2, 2, 4), dtype=string, numpy=
array([[[b'I love Arya', b"I don't like dancing",
         b"I don't like dancing", b"I don't like dancing"],
        [b"I don't like dancing", b'I love Arya',
         b"I don't like dancing", b"I don't like dancing"]],

       [[b"I don't like dancing", b"I don't like dancing",
         b'I love Arya', b"I don't like dancing"],
        [b"I don't like dancing", b"I don't like dancing",
         b"I don't like dancing", b'I love Arya']]], dtype=object)>

### Some math functions

In [137]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [138]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [143]:
tf.sqrt(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [146]:
tf.math.log(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [147]:
# computes log(exp(x) + 1)
tf.math.softplus(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.3132616, 2.126928 , 3.048587 , 4.01815  , 5.0067153, 6.0024757,
       7.0009117, 8.000336 , 9.000123 ], dtype=float32)>

In [149]:
tf.math.sigmoid(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.7310586 , 0.8807971 , 0.95257413, 0.98201376, 0.9933071 ,
       0.99752736, 0.99908894, 0.99966455, 0.9998766 ], dtype=float32)>

### Tensors and Numpy

In [151]:
J = tf.constant(np.array([1,1,1]))
J

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 1])>

In [152]:
numpy_array = np.array(J)
type(numpy_array)

numpy.ndarray

In [154]:
J.numpy(), type(J.numpy())

(array([1, 1, 1]), numpy.ndarray)

In [156]:
J.numpy()[0]

1

In [157]:
# Default data types
A1 = np.array([3., 7.])
A2 = tf.constant(A1)
A3 = tf.constant([3., 7.])
A1.dtype, A2.dtype, A3.dtype

(dtype('float64'), tf.float64, tf.float32)

**Operations on numpy array runs only on CPU and Operations on tensors can run on GPU and TPU**

### Running on GPU

In [159]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [163]:
tf.config.list_physical_devices("CPU")

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [164]:
tf.config.list_physical_devices("GPU")

[]

In [2]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Sat Aug  6 06:46:15 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

✔**Note: If we have a CUDA enabled GPU acces avaibale on colab, tensorflow will make use of it whenever possible**